{% target '/etc/config-curator.conf' %}# this file is auto generated by config-curator do not edit by hand
# generated at {{ __timestamp__ }}
# for {{ _hostname }}, id: {{ _structure_id }}

[config]
config_host: {{ config_host }}
config_proxy: {{ config_proxy }}
uuid: {{ _structure_config_uuid }}
id: {{ _structure_id }}

{% endtarget %}
