{% target '/etc/config-curator.conf' %}# this file is auto generated by config-curator do not edit by hand
# generated at {{ timestamp }}
# for device {{ description }}, id: {{ id }}

[config]
config_url:  {{ }}
config_proxy: {{ plato_proxy }}
uuid: {{ config_uuid }}
id: {{ id }}

{% endtarget %}
