#!/bin/sh

set -e

if [ -f /config ]
then
  /bin/postMessage "Getting Handler Resources..."
  . /config
  for URL in $RESOURCE_URL_LIST
  do
    echo "Retrieving Resource '$URL'..."
    wget -q -O- $URL | tar -C / -xz
  done
fi

# just incase a handler brought in libs/modules
ldconfig
depmod -a

/bin/postMessage "Starting Firmware Update..."

./firmware.py && rc=0 || rc=$?

if [ "$rc" -eq "20" ];
then
  exit 20
fi

if [ "$rc" -ne "0" ];
then
  /bin/signalAlert "Firmware Update Failed."
  exit 10
fi

/bin/postMessage "Firmware Update Complete."
/bin/signalComplete

exit 0
