{% target '/etc/config-curator.conf' %}# this file is auto generated by config-curator do not edit by hand
# this is the basic startup config that rpm style packagins requires, if config-curator is not installed, this fieldset
# is not needed

[config]
config_host: {{ config_host }}
config_proxy: {{ config_proxy }}

{% endtarget %}
