#!/bin/sh

set -e

DEBUG=0
NET_DEBUG=0
CONFIG_SRC="remote"
HTTP_PROXY=
INTERFACE="any"
INTERFACE_MAC=
IP_PROMPT=0
NO_IP=0
IP_ADDRESS=
GATEWAY=
NETMASK=
DNS_SERVER=
DNS_SEARCH_ZONE=
HOSTNAME=
CONTRACTOR_IP=
# if this changes update the disks.toml so the default is properly ignored
CONTRACTOR_HOST="http://contractor"
CONTRACTOR_PROXY=
CONFIG_UUID=
JOB_ID=
MEDIA_UUID=
MEDIA_LABEL=

error_happened()
{
  echo "And Error occured... "
  while true
  do
    # read does not timeout if set -e
    set +e
    read -t 1 IGNORE  #clear out any garbage that might of been entered
    read -s -n 1 -p "(R)eboot  (P)ower Off  (S)hell" RESPONSE
    set -e
    if [ "$RESPONSE" == "R" ] || [ "$RESPONSE" == "r" ]
    then
      /sbin/reboot
    elif [ "$RESPONSE" == "P" ] || [ "$RESPONSE" == "p" ]
    then
      /sbin/poweroff
    elif [ "$RESPONSE" == "S" ] || [ "$RESPONSE" == "s" ]
    then
      echo ""
      echo "Dropping to shell, type 'exit' to close shell..."
      /bin/cttyhack /bin/sh -l
    fi
  done
}

for x in $(cat /proc/cmdline)
do
  case $x in
    http_proxy=*)
      HTTP_PROXY=${x#http_proxy=}
      ;;
    interface=*)
      INTERFACE=${x#interface=}
      ;;
    interface_mac=*)
      INTERFACE_MAC=${x#interface_mac=}
      ;;
    ip_address=*)
      IP_ADDRESS=${x#ip_address=}
      ;;
    gateway=*)
      GATEWAY=${x#gateway=}
      ;;
    netmask=*)
      NETMASK=${x#netmask=}
      ;;
    dns_server=*)
      DNS_SERVER=${x#dns_server=}
      ;;
    dns_search_zone=*)
      DNS_SEARCH_ZONE=${x#dns_search_zone=}
      ;;
    hostname=*)
      HOSTNAME=${x#hostname=}
      ;;
    ip_prompt)
      IP_PROMPT=1
      ;;
    no_ip)
      NO_IP=1
      ;;
    contractor_ip=*)
      CONTRACTOR_IP=${x#contractor_ip=}
      ;;
    contractor_proxy=*)
      CONTRACTOR_PROXY=${x#contractor_proxy=}
      ;;
    contractor_host=*)
      CONTRACTOR_HOST=${x#contractor_host=}
      ;;
    debug)
      DEBUG=1
      ;;
    net_debug)
      NET_DEBUG=1
      ;;
    no_config)
      CONFIG_SRC="none"
      ;;
    local_config)
      CONFIG_SRC="local"
      ;;
    config_uuid=*)
      CONFIG_UUID="${x#config_uuid=}"
      ;;
    job_id=*)
      JOB_ID="${x#job_id=}"
      ;;
    media_uuid=*)
      MEDIA_UUID="${x#media_uuid=}"
      ;;
    media_label=*)
      MEDIA_LABEL="${x#media_label=}"
      ;;
  esac
done

CONTRACTOR_NAME=$(echo "$CONTRACTOR_HOST" | cut -d / -f3 | cut -d : -f1 )

echo "Contractor Name: '$CONTRACTOR_NAME'"
/bin/logger "contractor_host: $contractor_host"

if [ "x$CONTRACTOR_PROXY" != "x" ]
then
  PING_HOST="$(echo $CONTRACTOR_PROXY | awk -F/ '{print $3}')"
else
  PING_HOST=$CONTRACTOR_NAME
fi

# a udev script runs and checks this file, if an interface name it is in it, it will be auto dhcped
# handy for interface that like to disaapear on us (probaby due to firmware updates)
touch /tmp/auto-dhcp-interfaces

if grep -q bmc_idrac /proc/net/dev
then
  echo "Brinning up iDRAC interface..."
  /sbin/ip link set bmc_idrac up
  /sbin/udhcpc --interface=bmc_idrac --syslog --now
  NO_PROXY=$(ip route | grep bmc_idrac | cut -d ' ' -f1 )
  # just incase the interface and re-appears
  echo bmc_idrac >> /tmp/auto-dhcp-interfaces
fi

if grep -q bmc_rhi /proc/net/dev
then
  echo "Brinning up Redfish Host Interface interface..."
  /sbin/ip link set bmc_rhi up
  /sbin/udhcpc --interface=bmc_rhi --syslog --now
  NO_PROXY=$(ip route | grep bmc_rhi | cut -d ' ' -f1 )
  # just incase the interface and re-appears
  echo bmc_rhi >> /tmp/auto-dhcp-interfaces
fi

if [ "$NET_DEBUG" == "1" ]
then
  /bin/cttyhack /bin/sh -l
  /sbin/poweroff
fi

if [ "x$INTERFACE_MAC" != "x" ]
then
  INTERFACE=

  for iface in $( ls /sys/class/net | grep -v bond | grep -v lo | grep -v bmc_ );
  do
    if [ "$INTERFACE_MAC" == "$( cat /sys/class/net/$iface/address )" ];
    then
      INTERFACE=$iface
      break
    fi
  done

  if [ "x$INTERFACE" == "x" ]
  then
    echo "No network interface with MAC '$INTERFACE_MAC' found."
    error_happened
  fi
fi

if [ "$NO_IP" == "0" ]
then
  # dhcping is here and not in rcS so we can get a virtual console and to look at dhcp errors, if in rcS none of the virtual terminals start up till after we get an ip
  echo "Getting Ip..."
  if [ "$IP_PROMPT" == "1" ]
  then
    IS_OK=0
    while [ "$IS_OK" == "0" ]
    do
      read -t 1 IGNORE  #clear out any garbage that might of been entered
      echo "Enter blank Ip Address to DHCP."
      read -p "Ip Address: " tmp_IP_ADDRESS
      read -p "Net Mask: " tmp_NETMASK
      read -p "Gateway: " tmp_GATEWAY
      read -p "DNS Server: " tmp_DNS_SERVER
      read -p "DNS Search Zone: " tmp_DNS_SEARCH_ZONE
      if [ "x$INTERFACE" == "x" ]
      then
        read -p "Interface: " tmp_INTERFACE
      fi
      if [ "x$HTTP_PROXY" == "x" ]
      then
        read -p "HTTP Proxy: " tmp_HTTP_PROXY
      fi
      echo
      echo "Setting"
      echo "      Ip Address: $tmp_IP_ADDRESS"
      echo "         Netmask: $tmp_NETMASK"
      echo "         Gateway: $tmp_GATEWAY"
      echo "      DNS Server: $tmp_DNS_SERVER"
      echo " DNS Search Zone: $tmp_DNS_SEARCH_ZONE"
      if [ "x$INTERFACE" == "x" ]
      then
        echo "       Interface: $tmp_INTERFACE"
      else
        echo "       Interface: $INTERFACE (configured at boot)"
      fi
      if [ "x$HTTP_PROXY" == "x" ]
      then
        echo "      HTTP Proxy: $tmp_HTTP_PROXY"
      else
        echo "      HTTP Proxy: $HTTP_PROXY (configured at boot)"
      fi

      RESPONSE="_"
      while [ "$RESPONSE" != "Y" ] && [ "$RESPONSE" != "y" ] && [ "$RESPONSE" != "N" ] && [ "$RESPONSE" != "n" ]
      do
        read -s -n 1 -p "This Correct (Y/N)?" RESPONSE
      done

      if [ "$RESPONSE" == "Y" ] || [ "$RESPONSE" == "y" ]
      then
        IS_OK=1
      fi
      IP_ADDRESS=$tmp_IP_ADDRESS
      NETMASK=$tmp_NETMASK
      GATEWAY=$tmp_GATEWAY
      DNS_SERVER=$tmp_DNS_SERVER
      DNS_SEARCH_ZONE=$tmp_DNS_SEARCH_ZONE
      if [ "x$INTERFACE" == "x" ]
      then
        INTERFACE=$tmp_INTERFACE
      fi
      if [ "x$HTTP_PROXY" == "x" ]
      then
        HTTP_PROXY=$tmp_HTTP_PROXY
      fi
      echo
      echo
    done
  fi

  if [ "x$INTERFACE" == "x" ]
  then
    echo "No Interface specified, guessing eth0."
    INTERFACE="eth0"
  fi

  if [ "x$INTERFACE" != "xany" ]
  then
    if [ ! -e /sys/class/net/$INTERFACE ]
    then
      echo "No network interface named '$INTERFACE' found."
      error_happened
    fi
  fi

  echo "Starting Interface '$INTERFACE'..."
  /bin/logger "interface: $INTERFACE"

  if [ "x$HOSTNAME" == "x" ]
  then
    if [ "x$INTERFACE" == "xany" ]
    then
      HOSTNAME="mac$(cat /sys/class/net/e*/address | head -n1 | sed s/://g)" # make sure bond0 nor lo isn't included, lo's mac is 0 and bond*'s mac is usless without any members
      if [ "x$HOSTNAME" == "x" ]
      then
        HOSTNAME="nonet"
      fi
    else
      HOSTNAME="mac$(cat /sys/class/net/$INTERFACE/address | sed s/://g)"
    fi
  fi
  echo "Hostname is '$HOSTNAME'"
  /bin/logger "hostname: $HOSTNAME"
  hostname $HOSTNAME
  echo "127.0.1.1 $HOSTNAME" >> /etc/hosts
  echo "$HOSTNAME" > /etc/hostname

  if [ "x$CONTRACTOR_IP" != "x" ]
  then
    echo "$CONTRACTOR_IP $CONTRACTOR_NAME" >> /etc/hosts
  fi

  if [ "x$IP_ADDRESS" != "x" ]
  then
    if [ "x$INTERFACE" == "xany" ]
    then # mabey at some time just pick the first interface and put it on, or something else more deterministic
      echo "Can't use 'any' for interface for statically assigned ip"
      exit 1
    fi
    /bin/logger "Setting Ip to $IP_ADDRESS, netmask $NETMASK, gateway $GATEWAY on $IFACE"
    /sbin/ip addr flush dev $INTERFACE
    /sbin/ip link set $INTERFACE up
    /sbin/ip addr add $IP_ADDRESS/$NETMASK dev $INTERFACE
    /sbin/ip route add default via $GATEWAY dev $INTERFACE
    echo "domain $DNS_SEARCH_ZONE" > /etc/resolv.conf
    echo "nameserver $DNS_SERVER" >> /etc/resolv.conf
    rc=1
    counter=1
    while [ "x$rc" != "x0" ]
    do
      echo "Pinging Gateway '$GATEWAY', ($counter/10)...."
      ping -q -c4 $GATEWAY > /dev/null 2> /dev/null
      rc=$?
      counter=$(( counter + 1 ))
      if [ "x$rc" != "x0" ] && [ "$counter" -gt "10" ]
      then
        echo "Error trying to ping Gateway."
        error_happened
      fi
      if [ "x$rc" != "x0" ]
      then
        sleep 10
      fi
    done
  else
    echo "Getting ip address..."
    if [ "x$INTERFACE" == "xany" ]
    then
      INTERFACE_LIST="$( ls /sys/class/net/ | grep -v bond | grep -v lo | grep -v sit | sort)"
    elif [ "x$INTERFACE" != "x" ]
    then
      INTERFACE_LIST=$INTERFACE
    else
      echo "Error Interface name is blank..."
      error_happened
    fi

    if [ "x$INTERFACE_LIST" == "x" ]
    then
      echo "No interface(s) found"
      error_happened
    fi

    #/tmp/dhcp-interface created by lib/udhcpc/script
    rm -f /tmp/dhcp-interface
    while [ ! -f /tmp/dhcp-interface ]
    do
      for iface in $INTERFACE_LIST
      do
        echo "Bringing up '$iface'..."
        /sbin/ip link set $iface up
        echo -n "  Waiting ."
        counter=1
        while [ "x$(cat /sys/class/net/$iface/operstate)" != "xup" ] && [ "$counter" -lt "30" ]
        do
          echo -n "."
          counter=$(( counter + 1 ))
          sleep 1
        done
        echo
        if [ "x$(cat /sys/class/net/$iface/operstate)" != "xup" ]
        then
          echo "Interface '$iface' didn't come up, skipping..."
          echo "Random delay before trying next interface..."
          /bin/sleep $(( $RANDOM % 60 ))
          /sbin/ip link set $iface down
          continue
        fi
        echo "DHCPing on '$iface'..."
        RECORD_INTERFACE=yes /sbin/udhcpc --interface=$iface -x:hostname $HOSTNAME --vendorclass=t3ktondisk --timeout=10 --syslog --arping --release --now
        if [ -f /tmp/dhcp-interface ];
        then
          if [ "x$CONFIG_SRC" == "xremote" ]
          then
            echo "Resolving '$PING_HOST'..."
            nslookup $PING_HOST > /dev/null #TODO: find another way to do this, and remove nslookup from busybox.... it's the only thing with _res in busybox
            rc=$?
            if [ "x$rc" == "x0" ]
            then
              echo "Ping test to '$PING_HOST'..."
              ping -q -c2 $PING_HOST > /dev/null 2> /dev/null
              rc=$?
              if [ "x$rc" == "x0" ]
              then # we have a winner, let's get out of here
                break
              else
                echo "Interface '$( cat /tmp/dhcp-interface )' could not ping '$PING_HOST', skipping..."
                rm -f /tmp/dhcp-interface
              fi
            else
              echo "Interface '$( cat /tmp/dhcp-interface )' could not resolve '$PING_HOST', skipping..."
              rm -f /tmp/dhcp-interface
            fi
          else # not remote config, any ip will do, as far as we can tell anyway
            break
          fi
        fi
        /bin/kill $(ps | grep udhcpc | grep "interface=$iface" | cut -F 2)
        /bin/sleep 1
        /sbin/ip addr flush dev $iface
        /sbin/ip link set $iface down
        echo "Random delay before trying next interface...."
        /bin/sleep $(( $RANDOM % 120 ))
      done
    done
    INTERFACE=$(cat /tmp/dhcp-interface)
  fi

else
  hostname localhost
  echo "127.0.0.1 localhost" > /etc/hosts
fi

if [ "x$MEDIA_UUID" != "x" ]
then
  echo "Mounting '$MEDIA_UUID' to /media..."
  mkdir /media
  /sbin/udevadm trigger
  /sbin/udevadm settle
  mount UUID=$MEDIA_UUID /media
  if [ "$?" -ne "0" ];
  then
    echo "Error mounting media by UUID"
    error_happened
  fi
elif [ "x$MEDIA_LABEL" != "x" ]
then
  echo "Mounting '$MEDIA_LABEL' to /media..."
  mkdir /media
  /sbin/udevadm trigger
  /sbin/udevadm settle
  mount LABEL=$MEDIA_LABEL /media
  if [ "$?" -ne "0" ];
  then
    echo "Error mounting media by Label"
    error_happened
  fi
fi

if [ -x /config-init ]
then
  echo "Executing /config-init..."
  /config-init
fi

if [ -x /media/config-init ]
then
  echo "Executing /media/config-init..."
  /media/config-init
fi

if [ "x$HTTP_PROXY" != "x" ]
then
  echo "Setting 'http_proxy' to $HTTP_PROXY..."
  echo "Setting 'no_proxy' to $NO_PROXY..."
  /bin/logger "http_proxy: $HTTP_PROXY"
  /bin/logger "no_proxy: $NO_PROXY"
  export http_proxy=$HTTP_PROXY
  export https_proxy=$HTTP_PROXY
  export HTTP_PROXY
  export HTTPS_PROXY=$HTTP_PROXY
  export no_proxy=$NO_PROXY
  export NO_PROXY
fi

if [ "x$CONTRACTOR_PROXY" != "x" ]
then
  echo "Setting 'contractor_proxy' to $CONTRACTOR_PROXY..."
  /bin/logger "contractor_proxy: $CONTRACTOR_PROXY"
  export contractor_proxy=$CONTRACTOR_PROXY
fi

echo "Config Source is '$CONFIG_SRC'"
/bin/logger "config_src: $CONFIG_SRC"
if [ "x$CONFIG_SRC" == "xnone" ]
then
  export contractor_host="none://"

elif [ "x$CONFIG_SRC" == "xlocal" ]
then
  echo "Using Local Config..."
  if [ -r /media/config.json ]
  then
    export contractor_host="file://media/config.json"
  elif [ -r /config.json ]
  then
    export contractor_host="file://config.json"
  else
    echo "No Local Config!"
    error_happened
  fi

elif [ "x$CONFIG_SRC" == "xremote" ]
then
  if [ "$NO_IP" == "1" ]
  then
    echo "No IP to get config with!"
    error_happened
  fi

  export contractor_host=$CONTRACTOR_HOST
  export config_uuid=$CONFIG_UUID
  export job_id=$JOB_ID
  /bin/logger "config_uuid: $CONFIG_UUID"
  /bin/logger "job_id: $job_id"
fi

echo "Contractor config source '$contractor_host'"
/bin/logger "contractor_host: $contractor_host"

echo "Loading Job Config..."
if ! initJobConfig
then
  echo "Error getting Job Config!"
  error_happened
fi

if [ "x$CONFIG_SRC" == "xremote" ]
then
  CONFIG_REMOTE_URL="$(grep __pxe_template_location /etc/job.config | cut -d \" -f4)"
  echo "Getting Remote Config from '$CONFIG_REMOTE_URL'..."

  set +e
  wget -q -O /config $CONFIG_REMOTE_URL
  rc=$?
  set -e

  if [ "$rc" -ne "0" ]
  then
    set +e
    echo "Error getting config from '$CONFIG_REMOTE_URL'."
    read -t 1 IGNORE  #clear out any garbage that might of been entered
    read -t 30 -n 1 -p "Press \"D\" to enter Debug, any other key to reboot (30 second timeout)..." tmp_DEBUG
    set -e
    if [ "x$tmp_DEBUG" == "xd" ] || [ "x$tmp_DEBUG" == "xD" ]
    then
        echo -e "\nType \"exit\" to continue exit and reboot...\n"
        /bin/cttyhack /bin/sh -l
    fi
    echo -e "\Rebooting...\n"
    /sbin/reboot
    exit 0
  fi
fi

if [ "x$DEBUG" != "x1" ]
then
  set +e
  read -t 1 IGNORE  #clear out any garbage that might of been entered
  read -t 5 -n 1 -p "Press \"D\" to enter Debug, any other key to continue (5 second timeout)..." tmp_DEBUG
  set -e
  if [ "x$tmp_DEBUG" == "xd" ] || [ "x$tmp_DEBUG" == "xD" ]
  then
    DEBUG="1"
  else
    echo -e "\nContinuing...\n"
  fi
fi

if [ "x$DEBUG" == "x1" ]
then
  echo -e "\nType \"exit\" to continue to the task...\n"
  /bin/cttyhack /bin/sh -l
fi

set +e

# TODO: need to wrap do_task in a handler that will fail gracefully
./do_task
rc=$?
# exit status
# 20 - reboot
# 10 - Had an error, already ran signalAlert
# 0 - All good
# anything else - Had Error, no notification has happened yet

# echo "----- Log -----" >> /tmp/output.log
# /sbin/logread >> /tmp/output.log
# push /tmp/output.log to $OUTPUT_UPLOAD_URL
# file name is <hostname>-<endtime>-<uptime>.log

set -e

if [ "$rc" -eq "20" ]
then
  echo -e "\n\n\nRebooting...\n"
  /sbin/reboot
  exit 0
elif [ "$rc" -eq "10" ]
then
  error_happened
elif [ "$rc" -ne "0" ]
then
  echo "do_task returned '$rc'"
  signalAlert "do_task error"
  error_happened
fi

echo -e "\n\n\nPowering off...\n"
/sbin/poweroff
