#!/bin/sh
set -e
set -x

DISTRO_RELEASE="el$( lsb_release -sr | awk -F "." '{ print $1 }' )_1"

DEB_RELEASE="$( head debian-common/changelog -n1 | sed 's/.*(\([^)]*\)).*/\1/' )"
RELEASE="$( echo "$DEB_RELEASE" | cut -d '-' -f2 )"
VERSION="$( echo "$DEB_RELEASE" | cut -d '-' -f1 )"

PYTHON_VERSION_MAJOR=$(python3 --version | cut -d ' ' -f2 | cut -d '.' -f1)
PYTHON_VERSION_MINOR=$(python3 --version | cut -d ' ' -f2 | cut -d '.' -f2)

PYTHON_REQUIRES="python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}, python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}-dateutil"
PYTHON_PATH="python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}"

echo "Setting up for '$DISTRO_RELEASE' Version: '$VERSION' Release: '$RELEASE'"

TOPDIR="$( pwd )/rpmbuild"
SRCDIR="$( pwd )"

mkdir -p "$TOPDIR"
mkdir -p "$TOPDIR/RPMS"
mkdir -p "$TOPDIR/BUILD"
mkdir -p "$TOPDIR/BUILDROOT"

cat > rpmbuild/config.spec <<SPECFILE
%define _topdir $TOPDIR
%define _srcdir $SRCDIR

Name:           config-curator
Summary:        Configuration Curator
Version:        $VERSION
Release:        $RELEASE.$DISTRO_RELEASE
License:        Apache2
Group:          multiverse
Requires:       $PYTHON_REQUIRES
BuildArch:      noarch

%description
Merges Jinja2 templates with config retrieved via HTTP/JSON.  Can check for changes and show diffs.

%install
cd %{_srcdir}
make install DESTDIR=%{buildroot}/

%files
/usr/lib/$PYTHON_PATH/site-packages/*
/usr/sbin/*
/var/lib/config-curator/templates/*

%changelog

%post
FLAGS=""
HOST=http://contractor  # would be nice to get this from a db_get type thing
PROXY=

if test -n "\$CONFIG_CURATOR_HOST"
then
  HOST=\$CONFIG_CURATOR_HOST
fi

if test -n "\$CONFIG_CURATOR_PROXY"
then
  PROXY=\$CONFIG_CURATOR_PROXY
fi

if [ \$1 -eq 1 ]
then
   #First time install
  FLAGS="\$FLAGS -f --config-host \$HOST --config-uuid _new_"
fi

if [ "x$RET" != "x" ]
then
  FLAGS="\$FLAGS --config-proxy \$PROXY"
fi

/usr/sbin/config-curator \$FLAGS -c config-curator

%postun

SPECFILE
