#!/usr/bin/env python3

from libdrive.libenclosure import EnclosureManager

em = EnclosureManager()

print( "SCSI Generic\tModel" )

for enclosure in em.enclosure_list:
  print( '{0}\t{1}'.format( enclosure.scsi_generic, enclosure.model ) )
