all:

clean:

install:
	mkdir -p $(DESTDIR)/controller
	cp __init__.py $(DESTDIR)/controller
	cp client.py $(DESTDIR)/controller

test-requires:

test:

lint:

.PHONY: all clean install test-requires test lint
