#!/usr/bin/env python3

import sys

from controller import getClient, NoJobException

try:
  msg = sys.argv[ 1 ]
except KeyError:
  print( 'usage: {0} <message>' ).format( sys.argv[0] )

controller = getClient()

try:
  controller.signalAlert( msg )
except NoJobException:
  print( 'WARNING! No Job, aborting.' )

sys.exit( 0 )
