#!/usr/bin/env python3

import os
import json
from contractor.client import getClient

contractor = getClient()

contractor_config = contractor.getConfig()

disk_name = None
try:
  disk_name = open( '/etc/disk_name', 'r' ).read().strip()
except FileNotFoundError:
  pass

job_id = os.environ.get( 'job_id', None )

# uuid = contractor_config[ '_structure_config_uuid' ]
# uuid = contractor_config[ '_foundation_locator' ]
config = {}
config[ 'job' ] = {
                    'job_id': job_id,
                    'pxe_name': disk_name,
                    'cookie': '{0}_{1}'.format( job_id, disk_name )
                  }

config[ 'config' ] = contractor_config

open( '/etc/job.config', 'w' ).write( json.dumps( config, indent=2 ) )
