all:

clean:

install:
	mkdir -p $(DESTDIR)/lib/python3.6/contractor
	cp -a contractor/* $(DESTDIR)/lib/python3.6/contractor
	# cp postMessage $(DESTDIR)/bin
	# cp signalAlert $(DESTDIR)/bin
	# cp signalComplete $(DESTDIR)/bin
	cp setEnv $(DESTDIR)/bin

test-requires:

test:

lint:

.PHONY: all clean install test-requires test lint
