#!/usr/bin/env python3

import sys

from contractor.client import getClient

try:
  msg = sys.argv[ 1 ]
except KeyError:
  print( 'usage: {0} <message>' ).format( sys.argv[0] )

contractor = getClient( '/etc/job.config' )
contractor.login()
contractor.postMessage( msg )

sys.exit( 0 )
