#!/usr/bin/env python3

import sys
import json

from contractor.client import getClient

try:
  msg = sys.argv[ 1 ]
except KeyError:
  print( 'usage: {0} <message>' ).format( sys.argv[0] )

job = json.loads( open( '/etc/job.config', 'r' ).read() )[ 'job' ]

contractor = getClient()
contractor.setJobId( job[ 'job_id' ] )
contractor.login()
contractor.postMessage( msg )

sys.exit( 0 )
