#!/usr/bin/env python3

import os
import sys
from contractor.client import getClient

contractor = getClient()

config = contractor.getConfig()

for name in sys.argv[ 1: ]:
  try:
    os.environ[ name.upper() ] = config[ name ]
  except KeyError:
    pass
