#!/usr/bin/env python3

import sys
import json

config = json.loads( open( '/etc/job.config', 'r' ).read() )[ 'config' ]

for name in sys.argv[ 1: ]:
  try:
    value = config[ name ]
  except KeyError:
    continue

  if isinstance( value, str ):
    print( '{0}="{1}"'.format( name, value ) )

  elif isinstance( value, list ):
    print( '{0}="{1}"'.format( name, ' '.join( value ) ) )

  else:
    print( 'Unable to deal with type "{0}"'.format( type( value ) ) )
    sys.exit( 1 )
