#!/usr/bin/env python3

import sys
import json

from contractor.client import getClient


job = json.loads( open( '/etc/job.config', 'r' ).read() )[ 'job' ]

contractor = getClient()
contractor.setJobId( job[ 'job_id' ] )
contractor.login()

resp = contractor.request( 'call', '/api/v1/Foreman/BaseJob:{0}:(signalComplete)'.format( job[ 'job_id' ] ), { 'cookie': job[ 'cookie' ] } )

if resp != 'Recieved':
  print( 'WARNING! signaling failed: "{0}"'.format( resp ) )
  sys.exit( 1 )

sys.exit( 0 )
