#!/usr/bin/env python3

import sys
import json

from contractor.client import getClient, HTTPClient

contractor = getClient()

if not isinstance( contractor, HTTPClient ):
  sys.exit( 0 )

job = json.loads( open( '/etc/job.config', 'r' ).read() )[ 'job' ]

resp = contractor.request( 'call', '/api/v1/Foreman/BaseJob(signalComplete):{0}:'.format( job[ 'job_id' ] ), { 'cookie': job[ 'cookie' ] } )

if resp != 'Recieved':
  print( 'WARNING! signaling failed: "{0}"'.format( resp ) )
  sys.exit( 1 )

sys.exit( 0 )
