#!/bin/sh

echo "Doing Front"

/bin/postMessage "Wiping Front"

for item in $@;
do
  drive="$( echo $item | cut -d ':' -f 1 )"
  proc="$( echo $item | cut -d ':' -f 2 )"
  if [ "$proc" == "wipedrive" ];
  then
    $( wipedrive -q -i 10 --count 2 /dev/$drive > /dev/null ) &
  elif [ "$proc" == "trim" ];
  then
    $( wipedrive -q -r -i 10 --count 2 /dev/$drive > /dev/null ) &
  else
    $( dd if=/dev/zero of=/dev/$drive bs=512 count=2 2> /dev/null ) &
  fi
done

echo "Waiting..."
wait

echo "Doing Back"

/bin/postMessage "Wiping Back"

for item in $@;
do
  drive="$( echo $item | cut -d ':' -f 1 )"
  proc="$( echo $item | cut -d ':' -f 2 )"
  if [ "$proc" == "wipedrive" ];
  then
    $( wipedrive -q -i 10 --start $(( `driveinfo /dev/$drive | grep "^LBA Count:" | cut -d: -f2` - 2 )) /dev/$drive > /dev/null ) &
  elif [ "$proc" == "trim" ];
  then
    $( wipedrive -q -r -i 10 --start $(( `driveinfo /dev/$drive | grep "^LBA Count:" | cut -d: -f2` - 2 )) /dev/$drive > /dev/null ) &
  else
    $( dd if=/dev/zero of=/dev/$drive bs=512 count=1 skip=$(( `fdisk -s /dev/$drive` - 2 )) 2> /dev/null ) &
  fi
done

echo "Waiting..."
wait

echo "Done"

exit 0
