#!/bin/sh

#DISK: linux-installer

QUESTION_LIST=( "IP_ADDRESS" "PREFIX" "GATEWAY" "DNS_SERVER" "MIRROR_SERVER" "HOSTNAME" "DOMAIN" "SWAP_SIZE" "USE_PROXY" "PROXY" "IS_VM" "RAID_TYPE"  )
DESC_LIST=( "Ip Address" "Prefix" "Gateway" "DNS Server" "Mirror Server" "Hostname" "Domain Name" "Swap Size" "Use HTTP Proxy" "HTTP Proxy (ignored if use proxy is n)" "Is VM" "RAID Type (ignored if VM)" )
TYPE_LIST=( "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "yesno" "inputbox" "yesno" "menu:single_Single Disk_mirror_Mirror Two Disks_raid10_All disks into RAID 10_raid6_All disks into RAID 6_single-lvm_Single Disk LVM_dual-lvm_Two Disk LVM" )
DEFAULT_LIST=( "192.168.1.100" "24" "192.168.1.1" "192.168.1.1" "us.archive.ubuntu.com" "bionic" "local" "2048" "yes" "http://proxy:3128/" "no" "single"  )

INIT='#!/bin/sh

sed s/--MAC--/$( cat /sys/class/net/eth0/address )/ -i /config.json'

CONFIG='{
  "distro": "ubuntu",
  "distro_version": "bionic",
  "bootstrap_source": "http://__MIRROR_SERVER__/ubuntu",
  "_hostname": "__HOSTNAME__",
  "_console": "__CONFIG_CONSOLE__",
  "package_list": [ "openssh-server", "openssh-client" __PACKAGES__ ],
  "swap_size": "__SWAP_SIZE__",
  "http_proxy": "__PROXY__",
  "partition_scheme": "__PART_SCHEME__",
  "repo_list": [
    { "distribution": "bionic", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" },
    { "distribution": "bionic-updates", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" },
    { "distribution": "bionic-security", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" }
  ],
  "dns_servers": [ "__DNS_SERVER__" ],
  "dns_search": [ "__DOMAIN__" ],
  "_domain_name": "__DOMAIN__",
  "id": 0,
  "uuid": "00000000-0000-0000-0000-000000000000",
  "_interface_map": { "eth0": {
      "physical_location": "eth0",
      "address_list": [
        {
          "address": "__IP_ADDRESS__",
          "gateway": "__GATEWAY__",
          "netmask": "__NETMASK__",
          "prefix": "__PREFIX__",
          "primary": true,
          "alias_index": null,
          "vlan": null,
          "mtu": null,
          "auto": true
        }
      ],
      "mac": "--MAC--",
      "name": "eth0"
    }
  }
}'

CMDLINE="install	Install UbuntU Bionic - Static Network __HOSTNAME__	local_config __BOOT_PROXY__ ip_address=__IP_ADDRESS__ netmask=__NETMASK__ gateway=__GATEWAY__ dns_server=__DNS_SERVER__ hostname=__HOSTNAME__ dns_search_zone=__DOMAIN__ interface=eth0 __KERNEL_CONSOLE__"

EXTRA_LIST='contractor/linux-installer-profiles/var/www/static/disks/ubuntu-bionic-profile.tar.gz'

post_process()
{
  if [ "x$USE_PROXY" = "xyes" ];
  then
    BOOT_PROXY="http_proxy=$PROXY"
  else
    PROXY=""
    BOOT_PROXY=""
  fi

  if [ "x$IS_VM" == "xyes" ];
  then
    KERNEL_CONSOLE=""
    CONFIG_CONSOLE="console"
    PACKAGES=""
  else
    KERNEL_CONSOLE="console=tty1 console=ttyS1,115200n8"
    CONFIG_CONSOLE="/dev/ttyS1"
    PACKAGES=""
  fi

  if [[ "x$RAID_TYPE" == "xmirror" || "x$RAID_TYPE" == "xraid10" || "x$RAID_TYPE" == "xraid6" || "x$RAID_TYPE" == "xsingle-lvm" || "x$RAID_TYPE" == "xdual-lvm" ]] && [ "x$IS_VM" != "xyes" ];
  then
    PART_SCHEME="$RAID_TYPE"
  else
    PART_SCHEME="single"
  fi

  NETMASK=$(cdr2mask $PREFIX)
}

# https://serverfault.com/questions/54981/linux-command-line-tool-to-work-with-netmasks-cidr-notation
cdr2mask()
{
   # Number of args to shift, 255..255, first non-255 byte, zeroes
   set -- $(( 5 - ($1 / 8) )) 255 255 255 255 $(( (255 << (8 - ($1 % 8))) & 255 )) 0 0 0
   [ $1 -gt 1 ] && shift $1 || shift
   echo ${1-0}.${2-0}.${3-0}.${4-0}
}
