#!/bin/sh

#DISK: linux-installer

QUESTION_LIST=( "IP_ADDRESS" "NETMASK" "GATEWAY" "DNS_SERVER" "MIRROR_SERVER" "HOSTNAME" "DOMAIN" "SWAP_SIZE" "USE_PROXY" "PROXY" "IS_VM" "RAID_TYPE"  )
DESC_LIST=( "Ip Address" "Netmask" "Gateway" "DNS Server" "Mirror Server" "Hostname" "Domain Name" "Swap Size" "Use HTTP Proxy" "HTTP Proxy (ignored if use proxy is n)" "Is VM" "RAID Type (ignored if VM)" )
TYPE_LIST=( "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "inputbox" "yesno" "inputbox" "yesno" "menu:single_Single Disk_mirror_Mirror Two Disks_raid10_All disks into RAID 10_raid6_All disks into RAID 6_single-lvm_Single Disk LVM_dual-lvm_Two Disk LVM" )
DEFAULT_LIST=( "192.168.1.100" "255.255.255.0" "192.168.1.1" "192.168.1.1" "us.archive.ubuntu.com" "xenial" "local" "2048" "yes" "http://proxy:3128/" "no" "single"  )

CONFIG='DISTRO="ubuntu"
VERSION="xenial"
SOURCE="http://__MIRROR_SERVER__/ubuntu"

cat > /config.json << CONFIG_EOF
{
  "distro_version": "xenial",
  "hostname": "__HOSTNAME__",
  "packages": "openssh-server openssh-client __PACKAGES__",
  "swap_size": "__SWAP_SIZE__",
  "http_proxy": "__PROXY__",
  "partition_scheme": "__PART_SCHEME__",
  "repo_list": [
    { "distribution": "xenial", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": ["main"], "proxy": "__PROXY__" },
    { "distribution": "xenial-updates", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": ["main"], "proxy": "__PROXY__" },
    { "distribution": "xenial-security", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": ["main"], "proxy": "__PROXY__" }
  ],
  "dns_servers": [ "__DNS_SERVER__" ],
  "dns_search": [ "__DOMAIN__" ],
  "domain": "__DOMAIN__",
  "id": 0,
  "uuid": "00000000-0000-0000-0000-000000000000",
  "interface_list": [
    {
      "address_list": [
        {
          "address": "__IP_ADDRESS__",
          "gateway": "__GATEWAY__",
          "netmask": "__NETMASK__",
          "primary": true,
          "sub_interface": null,
          "tagged": false,
          "vlan": 0,
          "mtu": 1500
        }
      ],
      "mac": "--MAC--",
      "name": "eth0"
    }
  ]
}
CONFIG_EOF

sed s/--MAC--/$( cat /sys/class/net/eth0/address )/ -i /config.json
'

EXTLINUX='PROMPT 1
TIMEOUT 10
DEFAULT normal

LABEL normal
KERNEL /vmlinuz.img
APPEND initrd=/initrd.img local_config __BOOT_PROXY__ ip_address=__IP_ADDRESS__ netmask=__NETMASK__ gateway=__GATEWAY__ dns_server=__DNS_SERVER__ hostname=__HOSTNAME__ dns_search_zone=__DOMAIN__ interface=eth0
'

post_process()
{
  if [ "x$USE_PROXY" = "xyes" ];
  then
    BOOT_PROXY="http_proxy=$PROXY"
  else
    PROXY=""
    BOOT_PROXY=""
  fi

  if [ "x$IS_VM" == "xyes" ];
  then
    CONSOLE=""
    CONSOLE_BAUD=""
    PACKAGES=""
  else
    CONSOLE="ttyS1"
    CONSOLE_BAUD="115200"
    PACKAGES=""
  fi

  if [[ "x$RAID_TYPE" == "xmirror" || "x$RAID_TYPE" == "xraid10" || "x$RAID_TYPE" == "xraid6" || "x$RAID_TYPE" == "xsingle-lvm" || "x$RAID_TYPE" == "xdual-lvm" ]] && [ "x$IS_VM" != "xyes" ];
  then
    PART_SCHEME="$RAID_TYPE"
  else
    PART_SCHEME="single"
  fi
}
