#!/bin/sh

#DISK: linux-installer

QUESTION_LIST=( "MIRROR_SERVER" "HOSTNAME" "SWAP_SIZE" "USE_PROXY" "PROXY" "IS_VM" "RAID_TYPE"  )
DESC_LIST=( "Mirror Server" "Hostname" "Swap Size" "Use HTTP Proxy" "HTTP Proxy (ignored if use proxy is n)" "Is VM" "RAID Type (ignored if VM)" )
TYPE_LIST=( "inputbox" "inputbox" "inputbox" "yesno" "inputbox" "yesno" "menu:single_Single Disk_mirror_Mirror Two Disks_raid10_All disks into RAID 10_raid6_All disks into RAID 6_single-lvm_Single Disk LVM_dual-lvm_Two Disk LVM" )
DEFAULT_LIST=( "us.archive.ubuntu.com" "xenial" "2048" "yes" "http://proxy:3128/" "no" "single"  )

INIT='#!/bin/sh

sed s/--MAC--/$( cat /sys/class/net/eth0/address )/ -i /config.json'

CONFIG='{
  "distro": "ubuntu",
  "distro_version": "xenial",
  "bootstrap_source": "http://__MIRROR_SERVER__/ubuntu",
  "_hostname": "__HOSTNAME__",
  "_console": "__CONFIG_CONSOLE__",
  "package_list": [ "openssh-server", "openssh-client" __PACKAGES__ ],
  "swap_size": "__SWAP_SIZE__",
  "http_proxy": "__PROXY__",
  "partition_scheme": "__PART_SCHEME__",
  "repo_list": [
    { "distribution": "xenial", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" },
    { "distribution": "xenial-updates", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" },
    { "distribution": "xenial-security", "type": "apt", "uri": "http://__MIRROR_SERVER__/ubuntu/", "components": [ "main", "universe", "multiverse" ], "proxy": "__PROXY__" }
  ],
  "id": 0,
  "uuid": "00000000-0000-0000-0000-000000000000",
  "_interface_map": { "eth0": {
      "physical_location": "eth0",
      "address_list": [
        {
          "address": "dhcp",
          "primary": true,
          "alias_index": null,
          "vlan": null,
          "mtu": null,
          "auto": true
        }
      ],
      "mac": "--MAC--",
      "name": "eth0"
    }
  }
}'

CMDLINE="install	Install Ubuntu Xenial	local_config __BOOT_PROXY__ hostname=__HOSTNAME__ local_config interface=any"

EXTRA_LIST='contractor/linux-installer-profiles/var/www/static/disks/ubuntu-xenial-profile.tar.gz'

post_process()
{
  if [ "x$USE_PROXY" = "xyes" ];
  then
    BOOT_PROXY="http_proxy=$PROXY"
  else
    PROXY=""
    BOOT_PROXY=""
  fi

  if [ "x$IS_VM" == "xyes" ];
  then
    KERNEL_CONSOLE=""
    CONFIG_CONSOLE="console"
    PACKAGES=""
  else
    KERNEL_CONSOLE="console=tty1 console=ttyS1,115200n8"
    CONFIG_CONSOLE="ttyS1"
    PACKAGES=""
  fi

  if [[ "x$RAID_TYPE" == "xmirror" || "x$RAID_TYPE" == "xraid10" || "x$RAID_TYPE" == "xraid6" || "x$RAID_TYPE" == "xsingle-lvm" || "x$RAID_TYPE" == "xdual-lvm" ]] && [ "x$IS_VM" != "xyes" ];
  then
    PART_SCHEME="$RAID_TYPE"
  else
    PART_SCHEME="single"
  fi
}
