#!/bin/sh

set -e
#set -x

# $1 - name of dep
# $2 - build dir
# $3 - path to lib dir
# $4 - path to the downloaded source archive
# $5 - arch
# $6 - make paramaters

. deps/*_$1

cd $2

build ../../$4 $3 $5 "$6"

# build paramaters
# $1 - path to the downloaded source
# $2 - path to lib dir
# $3 - arch
# $4 - make paramaters
