#!/bin/sh

PWD=$(pwd)

install_base()
{
  # $1 - target root fs dir
  # $2 - source dir
  # $3 - dep build dir

  $PWD/scripts/setup_base "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps"
  $PWD/scripts/install_kernel "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps"
}

install_dep()
{
  #  $1 - name of dep
  #  $2 - target root fs dir
  #  $3 - source dir
  #  $4 - dep build dir

  . $PWD/deps/$1

  install "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps/$1"
}
