#!/bin/sh

set -e

PWD=$(pwd)

install_base()
{
  # $1 - target root fs dir
  # $2 - source dir
  # $3 - dep build dir

  $PWD/scripts/setup_base "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps"
  $PWD/scripts/install_kernel "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps"
}

install_dep()
{
  #  $1 - name of dep
  #  $2 - target root fs dir
  #  $3 - source dir
  #  $4 - dep build dir

  . $PWD/deps/$1

  install "$PWD/build.images/$ROOT_FS" "$PWD/src" "$PWD/build.deps/$1"
}

install_src()
{
  # for now we will do a big if statement, not all the src is "install" able

  if [ "x$1" = "xlibconfig" ]
  then
    DESTDIR="$PWD/build.images/$ROOT_FS" make -C "$PWD/src/libconfig" install
  elif [ "x$1" = "xlibdrive" ]
  then
    DESTDIR="$PWD/build.images/$ROOT_FS" make -C "$PWD/src/libdrive" install
  fi

}
