#!/bin/sh

set -e
#set -x

# $1 - target root fs dir
# $2 - source dir
# $3 - dep build dir

mkdir -p $1/boot

cp "$3/linux/arch/x86_64/boot/bzImage" $1/boot/vmlinuz

cp -f $( realpath $3/kmod/libkmod/.libs/libkmod.so ) $1/lib

cd $3/linux/ && INSTALL_MOD_PATH=$1 make modules_install
rm $1/lib/modules/*/build
rm $1/lib/modules/*/source
cp -f $3/kmod/tools/kmod $1/sbin
ln -sf kmod $1/sbin/lsmod
ln -sf kmod $1/sbin/rmmod
ln -sf kmod $1/sbin/insmod
ln -sf kmod $1/sbin/modinfo
ln -sf kmod $1/sbin/modprobe
ln -sf kmod $1/sbin/depmod
