#!/bin/bash
set -e
set -x

# $1 - output filename
# $2 - path to kernel
# $3 - path to initrd
# $4 - path to boot config
# $5 - path to boot menu (optional)

# size in 1k blocks, default is 60k ie 60meg disk
DISK_SIZE="68k"

MOUNT_POINT="build.images/mnt"

if ! which sfdisk parted > /dev/null
then
  print "sfdisk and/or parted is missing, please install"
  exit 1
fi

if [ ! -d $MOUNT_POINT ]
then
  mkdir -p $MOUNT_POINT
fi

if mountpoint -q $MOUNT_POINT
then
  echo "$MOUNT_POINT allready mounted, possibly a failed build needs to be cleaned up?"
  exit 1
fi

EFI_LD64="/usr/lib/syslinux/modules/efi64/ldlinux.e64"
EFI_BIN64="/usr/lib/SYSLINUX.EFI/efi64/syslinux.efi"

if [ ! -f "$EFI_BIN64"  ];
then
  echo "syslinux.efi not found install syslinux-efi"
  exit 1
fi

if [ $( id -u ) != 0 ]
then
  echo "Must be root"
  exit 1
fi

rm -f $1

echo "Creating image..."
dd if=/dev/zero of=$1 bs=1k count=$DISK_SIZE
drive_loop=$(losetup -f --show $1)
echo "Using loop device '$drive_loop' for image..."

echo "Formatting partition..."
mkfs.fat -F 12 -S 512 -r 512 -n "T3DISKS_EFI" $drive_loop

echo "Mounting partition..."
mount $drive_loop $MOUNT_POINT

echo "Copying files..."
mkdir -p $MOUNT_POINT/efi/boot/syslinux
cp $EFI_BIN64 $MOUNT_POINT/efi/boot/bootx64.efi
cp $EFI_LD64 $MOUNT_POINT/efi/boot/syslinux/ldlinux.e64
#cp /usr/lib/syslinux/modules/efi64/* $MOUNT_POINT/efi/boot/syslinux/
#cp /usr/lib/syslinux/modules/efi64/* $MOUNT_POINT/efi/boot/

# cp /home/peter/Projects/t3kton/disks/build.deps/syslinux/syslinux-6.03/efi64/com32/elflink/ldlinux/ldlinux.e64 $MOUNT_POINT/efi/boot/
# cp /home/peter/Projects/t3kton/disks/build.deps/syslinux/syslinux-6.03/efi64/efi/syslinux.efi $MOUNT_POINT/efi/boot/bootx64.efi

# cp /home/peter/Projects/t3kton/disks/build.deps/syslinux/syslinux/efi64/efi/syslinux.efi $MOUNT_POINT/efi/boot/bootx64.efi
# cp /home/peter/Projects/t3kton/disks/build.deps/syslinux/syslinux/efi64/com32/elflink/ldlinux/ldlinux.e64 $MOUNT_POINT/efi/boot/

cp $2 $MOUNT_POINT/efi/boot/syslinux/vmlinuz.img
cp $3 $MOUNT_POINT/efi/boot/syslinux/initrd.img
cp $4 $MOUNT_POINT/efi/boot/syslinux/syslinux.cfg

if [ "x$5" != "x" ] && [ -r "$5" ]
then
  cp -f $5 $MOUNT_POINT/EFI/BOOT/SYSLINUX/syslinux.mnu
fi

sleep 1
sync

echo "Unmounting..."
umount $MOUNT_POINT
losetup -d $drive_loop
