#!/bin/bash

set -e
#set -x

# $1 - output filename
# $2 - path to kernel
# $3 - path to initrd
# $4 - path to boot config file
# $5 - path config-init (optional)
# $6 - path config.json (optional)
# $7 - path to extras dir (optional)

ISO_BOOT="/usr/lib/ISOLINUX/isohdpfx.bin"

if ! which xorriso > /dev/null
then
  echo "xorriso not found install xorriso"
  exit 1
fi

if [ ! -f "$ISO_BOOT"  ];
then
  echo "isolinux.bin not found install isolinux"
  exit 1
fi

WORK_DIR="build.images/isotmp"

if [ -d $WORK_DIR ]
then
  rm -ifr ./${WORK_DIR}/
fi

rm -f $1

mkdir -p $WORK_DIR

echo "Copying in kernel and image..."
cp $2 $WORK_DIR/vmlinuz.img
scripts/inject_initrd $3 $WORK_DIR/initrd.img $5 $6 $7

echo "Setting up Legacy Boot..."
scripts/makelegacyboot $WORK_DIR "iso" $4

echo "Building efiboot.img..."
sudo scripts/makeefiboot $WORK_DIR/isolinux/efiboot.img $2 $WORK_DIR/initrd.img $4

xorriso -as mkisofs \
  -o $1 \
  -isohybrid-mbr $ISO_BOOT \
  -c isolinux/boot.cat \
  -b isolinux/isolinux.bin \
   -no-emul-boot -boot-load-size 4 -boot-info-table \
  -eltorito-alt-boot \
  -e isolinux/efiboot.img \
   -no-emul-boot \
   -isohybrid-gpt-basdat \
  $WORK_DIR

echo "Done!"
