#!/bin/sh

set -e
set -x

# $1 - target root fs dir
# $2 - source dir
# $3 - dep build dir

# install busybox
cp $3/busybox/busybox $1/bin
mkdir -p $1/usr/bin
ln -sf /bin/env $1/usr/bin/env

# install source binaries
cp $2/ttytee/ttytee $1/sbin
cp $2/nscd/nscd $1/sbin

# install required libraries
# TODO compile libc and install that instead of taking it from the host system
mkdir $1/lib64
cp /lib64/ld-linux-x86-64.so.2 $1/lib64
cp `which ldconfig.real` $1/sbin/ldconfig

for LIB in /lib/x86_64-linux-gnu/libc-2.27.so /lib/x86_64-linux-gnu/libm-2.27.so \
/lib/x86_64-linux-gnu/libutil-2.27.so /lib/x86_64-linux-gnu/libdl-2.27.so \
/lib/x86_64-linux-gnu/libpthread-2.27.so /lib/x86_64-linux-gnu/libnsl-2.27.so \
/lib/x86_64-linux-gnu/libnss_compat-2.27.so /lib/x86_64-linux-gnu/libnss_files-2.27.so \
/lib/x86_64-linux-gnu/libnss_dns-2.27.so /lib/x86_64-linux-gnu/libresolv-2.27.so \
/lib/x86_64-linux-gnu/librt-2.27.so /lib/x86_64-linux-gnu/libcrypt-2.27.so
do
  cp -L $LIB $1/lib
done

sudo chroot $1 /sbin/ldconfig -l /lib/libc-2.27.so -l /lib/libm-2.27.so


# setup locale
cp `which locale` $1/sbin/locale
mkdir -p $1/usr/lib/locale
localedef --prefix=$1 -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# have these two use the function in disk_functions?
./scripts/install_dep udev $1 $2 $3
./scripts/install_dep python $1 $2 $3

# install controller libs
cp -a $2/controller $1/lib/python3.6/
