#!/bin/sh

set -e
set -x

# install busybox
cp $3/busybox/busybox $1/bin
mkdir -p $1/usr/bin
ln -sf /bin/env $1/usr/bin/env

# install source binaries
cp $2/ttytee/ttytee $1/sbin
cp $2/nscd/nscd $1/sbin

# install required libraries
# TODO compile libc and install that instead of taking it from the host system
cp /lib64/ld-linux-x86-64.so.2 $1/lib64
cp `which ldconfig.real` $1/sbin/ldconfig

for LIB in /lib/x86_64-linux-gnu/libc-2.26.so /lib/x86_64-linux-gnu/libm-2.26.so \
/lib/x86_64-linux-gnu/libutil-2.26.so /lib/x86_64-linux-gnu/libdl-2.26.so \
/lib/x86_64-linux-gnu/libpthread-2.26.so /lib/x86_64-linux-gnu/libnsl-2.26.so \
/lib/x86_64-linux-gnu/libnss_compat-2.26.so /lib/x86_64-linux-gnu/libnss_files-2.26.so \
/lib/x86_64-linux-gnu/libnss_dns-2.26.so /lib/x86_64-linux-gnu/libresolv-2.26.so \
/lib/x86_64-linux-gnu/librt-2.26.so /lib/x86_64-linux-gnu/libcrypt-2.26.so
do
  cp -L $LIB $1/lib
done

ln -sf libc-2.26.so $1/lib/libc.so.6
ln -sf libm-2.26.so $1/lib/libm.so.6

./scripts/install_dep udev $1 $2 $3
./scripts/install_dep python $1 $2 $3

# install plato libs
cp -a $2/platoclient $1/lib/python3.6/
