#!/bin/sh

set -e
set -x

# $1 - target directory of build root

cp scripts/setup_build_root_chroot $1

fakechroot fakeroot chroot $1 /bin/bash -l -c '/setup_build_root_chroot'

# yes this is odd that we pass the real path to something in chroot, but ldconfig is cutting some corner that fakechroot can't handle
fakechroot fakeroot chroot $1 /bin/bash -l -c "ldconfig.real -C $1/etc/ld.so.cache"

# copy in support files
cp -ap configs $1
cp scripts/build_dep_chroot $1

# setup linux boot image

pngtopnm logo.png | pnmscale -xsize=64 -ysize=64 > /tmp/logo_resized.ppm
ppmquant 224 /tmp/logo_resized.ppm | pnmnoraw > $1/configs/logo_linux_clut224.ppm
# some of this pipeline dosen't like the intermediate files, have to try again when we move to 24.04
# pnmnorm /tmp/logo_resized.ppm | pgmtopbm -thresh | pbmtoascii -2x4 > $1/configs/logo.ascii

# for now use caca-utils, when we switch to netpnm remove caca-utils from the packages list in the Makefile
img2txt -f utf8 -H 25 /tmp/logo_resized.ppm > $1/configs/logo.ascii

cat $1/configs/logo.ascii| sed s#\$#'\\n\"\\'# | sed s#\^#\"# > $1/configs/logo.h
