#!/bin/sh

set -e

/bin/postMessage "Starting Linux Install..."

ttytee -d /dev/instout /dev/tty4 /tmp/detail.log

./installer.py && rc=0 || rc=$?

if [ "$rc" -ne "0" ];
then
  /bin/signalAlert "Linux Install Failed."
  exit 10
fi

/bin/postMessage "Linux Install Complete."
/bin/signalComplete

exit 0
