#!/bin/sh

set -e

if [ -f /config ]
then
  /bin/postMessage "Getting Profile..."
  . /config
  for URL in $PROFILE_URL_LIST
  do
    wget -O - $URL | tar -C / -xz
  done
fi

/bin/postMessage "Starting Linux Install..."

ttytee -d /dev/instout /dev/tty4 /tmp/detail.log

./installer.py && rc=0 || rc=$?

if [ "$rc" -ne "0" ];
then
  /bin/signalAlert "Linux Install Failed."
  exit 10
fi

/bin/postMessage "Linux Install Complete."
/bin/signalComplete

exit 0
