#!/usr/bin/env python3

import sys
import os

from platoclient.libplatopxe import PlatoPXE, PlatoPxeNoJobException

platopxe = PlatoPXE( host=os.environ.get( 'plato_host', 'http://plato' ), proxy=os.environ.get( 'plato_proxy', None ) )

try:
  platopxe.signalComplete()
  print( 'Complete Signal Sent.' )
except PlatoPxeNoJobException:
  print( 'WARNING! No Job, aborting.' )

sys.exit( 0 )
