#!/bin/sh

set -e
set -x

ROOT_FS="linux-installer"

. scripts/disk_functions

install_base "mod"

install_dep "mdadm"
install_dep "lvm2"
install_dep "parted"
install_dep "e2fsprogs"
install_dep "xfsprogs"
install_dep "dosfstools"
install_dep "gpgv"
install_dep "debootstrap"
install_dep "pkgdetails"
install_dep "squashfs"

install_src "libconfig"
install_src "libdrive"
