#!/bin/sh

set -e

DEP_LIST="mdadm lvm2 parted e2fsprogs xfsprogs dosfstools libgpg-error libgcrypt gpgv debootstrap pkgdetails zstd squashfs bcache-tools efivar efibootmgr"
SRC_LIST="libconfig libdrive"

image_extra()
{
  :
}
