#!/bin/sh

set -e
set -x

ROOT_FS="utility"

. scripts/disk_functions

install_base

install_dep "ssh"
install_dep "lldp"
install_dep "mdadm"
install_dep "lvm2"
install_dep "parted"
install_dep "e2fsprogs"
install_dep "dosfstools"
install_dep "gpgv"

install_src "libdrive"
