#!/bin/sh

set -e

DEP_LIST="ssh lldp mdadm lvm2 parted e2fsprogs xfsprogs dosfstools libgpg-error libgcrypt gpgv squashfs ipmitool ntp bcache-tools pciutils"
SRC_LIST="libdrive"

# add EFI tools

image_extra()
{
  :
}