#!/bin/sh

set -e

eval $( /bin/setEnv timezone ntp_servers )

if [ "x$ntp_servers" == "x" ]
then
  ntp_servers="0.pool.ntp.org 1.pool.ntp.org"
fi

if [ "x$timezone" == "x" ]
then
  timezone="utc"
fi

/bin/postMessage "Starting Time Sync..."

echo "Timezone '$timezone'"
echo "NTP Server(s) '$ntp_servers'"
echo "Curent Time..."
date

echo "# By default, exchange time with everybody, but don't allow configuration.
restrict -4 default kod notrap nomodify nopeer noquery limited
restrict -6 default kod notrap nomodify nopeer noquery limited

" > /etc/ntp.conf

for server in $ntp_servers
do
  echo "server $server iburst" >> /etc/ntp.conf
done

echo "Updating time..."
/bin/ntpd -dnNq  && rc=0 || rc=$?

echo "Now it is..."
date

if [ "$rc" -ne "0" ];
then
  /bin/signalAlert "Time Sync Failed."
  exit 10
fi

/bin/postMessage "Time Sync Complete."
/bin/signalComplete

exit 0
