#!/bin/sh

set -e

/bin/postMessage "Starting Time Sync..."

/bin/ntpd -d -q -p $TIMESERVER && rc=0 || rc=$?

if [ "$rc" -ne "0" ];
then
  /bin/signalAlert "Time Sync Failed."
  exit 10
fi

/bin/postMessage "Time Sync Complete."
/bin/signalComplete

exit 0
